on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Run script file
        run: |
          git config user.name "ZenProjectGit's bot"
          git config user.email "zen1993626@gmail.com"
          chmod +x ./scrapper.sh
          . ./scrapper.sh
          chmod +x ./sort.sh
          bash sort.sh launchDate --export
        shell: bash
